feat: 450.66 release

diff --git a/debian/nvidia-dkms-450.postinst b/debian/nvidia-dkms-450.postinst
--- a/debian/nvidia-dkms-450.postinst
+++ b/debian/nvidia-dkms-450.postinst
@@ -1,5 +1,5 @@
 #!/bin/sh
-# postinst script for nvidia-kernel-common-450
+# postinst script for nvidia-dkms-450
 #
 # see: dh_installdeb(1)
 #
@@ -8,6 +8,27 @@
 # Authors: Alberto Milone
 set -e
 
+PACKAGE_NAME=nvidia
+CVERSION=450.66
+CVERSION=${CVERSION#*really.}
+
+
+ARCH=`dpkg --print-architecture`
+case $ARCH in
+    amd64)
+        ARCH="x86_64"
+        ;;
+    i386)
+        ARCH="i686"
+        ;;
+    armhf)
+        ARCH="armhf"
+        ;;
+    *)
+        echo "WARNING: unsupported arch: $ARCH"
+        ARCH="$ARCH"
+        ;;
+esac
 
 # Check the existence of a kernel named as $1
 _is_kernel_name_correct() {
@@ -85,6 +106,18 @@ get_newest_kernel() {
 
 case "$1" in
     configure)
+        # Deal with alternatives
+
+        # Clean up any previous non-multi-arch alternatives
+        if [ -n "$(update-alternatives --list gl_conf 2>/dev/null)" ]; then
+            set -a $(update-alternatives --list gl_conf 2>/dev/null)
+            while [ $# -ge 1 ] && [ "$#" != "configure" ]; do
+                ALTERNATIVE=${1}
+                update-alternatives --remove gl_conf $ALTERNATIVE
+                shift
+            done
+        fi
+
         CURRENT_KERNEL=$(uname -r)
         NEWEST_KERNEL=$(get_newest_kernel "$CURRENT_KERNEL")
 
@@ -97,6 +130,15 @@ case "$1" in
                 /usr/sbin/update-initramfs -u -k $CURRENT_KERNEL
             fi
         fi
+
+        # Enable any quirks for the driver
+        if [ `which quirks-handler` ]; then
+           quirks-handler -e $PACKAGE_NAME -v
+        fi
+
+        # Build the kernel module
+        /usr/lib/dkms/common.postinst $PACKAGE_NAME $CVERSION /usr/share/$PACKAGE_NAME $ARCH $2
+        exit $?
         ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
